---
- hosts: localhost
  become: True
  gather_facts: true
  vars:
    domain: "{{ prestashop_lb_name }}{{ azure_suffix }}"
  vars_files:
    - vars/main.yml

  roles:
    - { role: ansible-init-raid }
    - { role: geerlingguy.apache }
    - { role: geerlingguy.php }
    - { role: geerlingguy.apache-php-fpm }
    - { role: carlosbuenosvinos.ansistrano-deploy }
    - { role: ansible-role-mysql }

  tasks:
    - name: "Install prestashop default shop"
      shell: >
        php {{ prestashop_dir }}/install/index_cli.php
        --domain="{{ domain | quote }}"
        --db_server="localhost"
        --db_name="{{ prestashop_dbname | quote }}"
        --db_user="{{ prestashop_user | quote }}"
        --db_password="{{ prestashop_password | quote }}"
        --firstname="{{ prestashop_firstname | quote }}"
        --lastname="{{ prestashop_lastname | quote }}"
        --password="{{ prestashop_password | quote }}"
        --email="{{ prestashop_email | quote }}"
        --newsletter=0
        --send_email=0
      register: php_result

    - name: "Remove Install Directory"
      file: path="{{ prestashop_dir }}/install" state=absent
      when: php_result.rc == 0

    - name: "Finalize files permission on {{ documentroot }}"
      file: dest="{{ documentroot }}" state=directory
            owner="{{ prestashop_owner }}" group="{{ prestashop_group }}"
            recurse=yes
